### ISSUE TITLE
feature request : add entice

### ISSUE THREAD

**Issue by vtorri** [batden/esteem#1]
entice is a small image viewer like eog. It's WIP though, and can be found here : 

https://github.com/vtorri/entice

**Comment by batden** [comment]
Hello Vincent,
Yeah, I already use Entice and it looks good.
We do plan to add Entice in the script. Well, I was waiting for Entice to land in the Enlightenment git repositories...
Do you intend to move your project to the Enlightenment repo?

**Comment by vtorri** [comment]
hello
that is something that is possible. I have to talk to raster for that.

btw, i plan to add meson support to enventor

**Comment by vtorri** [comment]
see https://phab.enlightenment.org/D12240 for a first  step

**Comment by batden** [comment]
Ok, thanks.

**Comment by batden** [comment]
Entice has been added to the script :)

**Comment by vtorri** [comment]
thanks :)
