### ISSUE TITLE
unsupported OS 

### ISSUE THREAD

**Issue by uciharis** [batden/esteem#20]
hi, im interested to use this script

however i got a few trouble like this after ran ./esteem.sh

`UNSUPPORTED OPERATING SYSTEM [ Ubuntu 22.04.3 LTS ]. `

i need your  help sir

**Comment by batden** [comment]
Hello,
You are probably using the wrong script.
You need to run elluminate.sh on Ubuntu 22.04.3 LTS!

**Comment by uciharis** [comment]
> Hello, You are probably using the wrong script. You need to run elluminate.sh on Ubuntu 22.04.3 LTS!

mr batden, im sorry i am unable to see file "elluminate.sh",
would you show me the location file please

**Comment by batden** [comment]
No problem. We all make errors.
