### ISSUE TITLE
debug mode?

### ISSUE THREAD

**Issue by ml1050** [batden/esteem#8]
Hi,

Is there a way to build enlightenment in debug mode?

Thanks

**Comment by batden** [comment]
I may add a debug option to meetse (companion script) in the near future.
For now, here are some hints.

The recommended way is to rebuild the EFL and E with **Asan** (everything should already be installed). See:
https://www.enlightenment.org/contrib/efl-debug?s[]=asan
for more details.

According to the doc, you need to export the following lines:
export ASAN_OPTIONS=detect_odr_violation=0:detect_leaks=0:abort_on_error=1:new_delete_type_mismatch=0
export CFLAGS="-O0 -g3"
in ~/.bash_alias (or elsewhere)

Then recompile EFL and E:
cd /path/to/source/<efl> ... <enlightenment>
meson --reconfigure -Db_sanitize=address build
(it may be useful to add wayland support in both programs to launch e with enlightenment_start... )
ninja -C build
sudo ninja -C build install

The rest is up to you...

Of course, GDB can be used too...
By the way, there is a nice little script in the enlightenment source dir that you can try. It's fun, run:
./xdebug.sh

**Comment by ml1050** [comment]
Thanks for your answer, I'll give it a try tomorrow.

**Comment by batden** [comment]
After some tests, the following actions seem to work well to perform debugging activities.

export ASAN_OPTIONS environment variables...

_For EFL_
Delete the build dir and build from scratch with:
meson -Db_sanitize=address -Dwl=true -Dlua-interpreter=lua -Dbuildtype=debugoptimized build
ninja -C build
sudo ninja -C build install
sudo ldconfig

_For enlightenment_
Delete the build dir and build from scratch with:
meson -Db_sanitize=address -Dwl=true -Dbuildtype=debugoptimized  build
ninja -C build
sudo ninja -C build install

_For Terminology (recommended)_
Delete the build dir and build from scratch with:
meson -Db_sanitize=address -Dbuildtype=debugoptimized  build
ninja -C build
sudo ninja -C build install
