### ISSUE TITLE
entice and edi errors

### ISSUE THREAD

**Issue by jlslinux** [batden/esteem#9]
Running custom install script '/home/jls/sorgenti/sources/e25/edi/data/extra/templates/../../../scripts/world_read.sh /usr/local/share/edi/templates/templates.edj'
Running custom install script '/home/jls/sorgenti/sources/e25/edi/data/extra/examples/../../../scripts/world_read.sh /usr/local/share/edi/examples/examples.edj'
Running custom install script '/home/jls/sorgenti/sources/e25/edi/data/themes/../../scripts/world_read.sh /usr/local/share/edi/themes/white.edj'
Running custom install script '/home/jls/sorgenti/sources/e25/edi/data/themes/../../scripts/world_read.sh /usr/local/share/edi/themes/solarized.edj'
Running custom install script '/home/jls/sorgenti/sources/e25/edi/data/themes/../../scripts/world_read.sh /usr/local/share/edi/themes/solarized_dark.edj'

Compilation and linking time:
00 hr 00 min 44 sec
./esteem.sh: riga 417: cd: /home/jls/sorgenti/sources/e25/entice: File o directory non esistente

Updating entice...

Già aggiornato.

Using 'PKG_CONFIG_PATH' from environment with value: '/usr/local/lib/pkgconfig'
Using 'PKG_CONFIG_PATH' from environment with value: '/usr/local/lib/pkgconfig'
The Meson build system
Version: 0.56.2
Source dir: /home/jls/sorgenti/sources/e25/edi
Build dir: /home/jls/sorgenti/sources/e25/edi/build
Build type: native build
Project name: edi
Project version: 0.8.99
Using 'CC' from environment with value: 'ccache gcc'
Using 'LDFLAGS' from environment with value: '-L/usr/local/lib'
Using 'CPPFLAGS' from environment with value: '-I/usr/local/include'
C compiler for the host machine: ccache gcc (gcc 11.2.0 "gcc (Ubuntu 11.2.0-7ubuntu2) 11.2.0")
C linker for the host machine: gcc ld.bfd 2.37
Using 'CC' from environment with value: 'ccache gcc'
Using 'LDFLAGS' from environment with value: '-L/usr/local/lib'
Using 'CPPFLAGS' from environment with value: '-I/usr/local/include'
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Using 'PKG_CONFIG_PATH' from environment with value: '/usr/local/lib/pkgconfig'
Run-time dependency elementary found: YES 1.26.99
Program pkg-config found: YES (/usr/bin/pkg-config)
Library intl found: YES
Program bear found: YES (/usr/bin/bear)
Has header "clang-c/Index.h" : NO

meson.build:73:4: ERROR: Problem encountered: Clang header not found!

**Comment by batden** [comment]
Thank you for the report.

> ./esteem.sh: riga 417: cd: /home/jls/sorgenti/sources/e25/entice: File o directory non esistente

Well, the message says it all:
Entice source code is missing (something probably went wrong during the download).

You can manually install it with:
cd /home/jls/sorgenti/sources/e25
git clone https://github.com/vtorri/entice
cd entice
meson build
ninja -C build

> meson.build:73:4: ERROR: Problem encountered: Clang header not found!

This is less trivial...

Edi builds fine on Focal Fossa and [Impish Indri](https://pastebin.com/Xvpm6vvd), but fails on Jammy Jellyfish.
I suspect some Meson quirks concerning the latter but I'm still investigating the issue.

Could you please post the output of the following command to help troubleshoot the issue?

**Comment by batden** [comment]
Oops, here it is:

apt-mark showmanual

Thanks
